[features]
seeds = false
skip-lint = false
[programs.devnet]
solquad = "3sd5iCCNUngPFu9QwgeTACP9KiiPaCt1bfBbsCjL64u3"

[programs.localnet]
solquad = "5sFUqUTjAMJARrEafMX8f4J1LagdUQ9Y8TR8HwGNHkU8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
